### ISSUE TITLE
Errors while adding packages

### ISSUE THREAD

**Issue by KyleKing** [clinical-meteor/accounts-famous-dead-people#1]
I love the idea for the app, but I'm having trouble adding it to my app.

```
 => Errors while adding packages:

While checking for clinical:accounts-famous-dead-people@1.0.0:
error: No compatible build found
```

**Comment by awatson1978** [comment]
Really? Hmm.  Give me a couple of days, and let me chck on this.

**Comment by KyleKing** [comment]
I'm able to download other packages. I think it might be something with how the package is deployed on Atmosphere, if that helps.

**Comment by awatson1978** [comment]
Okay, this should be fixed.  I forgot to add `api.versionsFrom('1.0.3.1')` in the package.js file.  Run a `meteor reset` and `meteor update clinical:accounts-famous-dead-people` or simply `meteor update` to get the latest package.  

You can find a demo app using the package here:
http://womens-history-month.meteor.com/

The men's images are also in the package, but are filtered in that particular demo.  

Anyhow, looking forward to seeing what you do with it!
